### ISSUE TITLE
Login with Google Account does not work anymore

### ISSUE THREAD

**Issue by phaus** [play-modules/modules.playframework.org#22]
The Login over Google (oAuth 2 i guess) does not work anymore:

![oauth_google_fails](https://f.cloud.github.com/assets/346361/631875/88fa42cc-d1d5-11e2-819d-fe17dfb3a876.png)

**Comment by pvillega** [comment]
Thanks for the report, checking!

**Comment by pvillega** [comment]
Fixed, the issue was caused by the www subdomain as the key was registered only against the main domain. The key has been updated to accept both domain and www subdomain
